{-|
A replacement for the standard "Prelude" when working with stylesheets written
in the "Clay" DSL.

Reexports the non-conflicting parts of "Prelude", all of "Control.Monad",
almost all of the generally useful parts of the "Clay" package itself, and
provides a variety of useful selectors that allow writing styles for the
sheets generated by this library in terms of the building blocks of this
package: fields.

Do note that this module does /not/ reexport any of the named colors from
"Clay.Color" or the element selectors from "Clay.Elements"! Those are available
for (qualified) import under "Roll20.CSS.Colors" and "Roll20.CSS.Elements".
-}
module Roll20.CSS
    ( 
    -- * Smart selectors
    -- ** Fields
      field, repField
    , FieldType(..)
    , fieldType
    , fieldReadOnly
    , valueEq, valueNotEq

    -- ** Buttons
    , actionButton, rollButton

    -- ** Tabs
    , SheetMode(..)
    , tabMode

    -- * @clay@ reexports
    , module Clay.Background
    , module Clay.Border
    , module Clay.Box
    , module Clay.Color
    , module Clay.Common
    , module Clay.Display
    , module Clay.Dynamic
    , module Clay.Flexbox
    , module Clay.Font
    , module Clay.Geometry
    , module Clay.Grid
    , module Clay.Pseudo
    , module Clay.Selector
    , module Clay.Size
    , module Clay.Stylesheet
    , module Clay.Text

    -- * @base@ reexports
    , module Control.Monad
    , module Prelude
    ) where

import Control.Monad
import Prelude hiding ( all, not, round, rem, repeat )

import Clay.Background
import Clay.Border
import Clay.Box
import Clay.Color ( Color
                  , rgba, rgb, hsla, hsl, grayish, transparent
                  , setR, setG, setB, setA
                  , toRgba, toHsla
                  , (*.), (+.), (-.), clamp, lighten, darken, lerp
                  )
import Clay.Common
import Clay.Display
import Clay.Dynamic ( UserSelect, userSelect, selectText )
import Clay.Flexbox hiding ( flex, FlexWrap, flexWrap, nowrap, wrap, wrapReverse )
import Clay.Font
import Clay.Geometry
import Clay.Grid
import Clay.Pseudo hiding ( root )
import Clay.Selector hiding ( (**) )
import Clay.Size
import Clay.Stylesheet ( StyleM(..), Css
                       , key, prefixed, (-:)
                       , (?), (<?), (&)
                       , root
                       , pop
                       , MediaType(..), Feature(..)
                       , query, queryNot, queryOnly
                       , important, importUrl
                       )
import Clay.Text

import Roll20.CSS.Selectors
